const cartTypes = {
  TOGGLE_CART_DROPDOW: "TOGGLE_CART_DROPDOW",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
};

export default cartTypes;
